spring:
  application:
    name: account-service
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: default
