spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://postgres:5432/customerdb
    username: bank
    password: bankpass123

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
