spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        native:
          search-locations: classpath:/config-repo

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
