spring:
  application:
    name: batch-service

  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:postgresql://postgres:5432/batchdb
    username: bank
    password: bankpass123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always # Auto-crea tablas y secuencias
    job:
      enabled: false

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,batch
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.duoc.bank.batch: INFO
    org.springframework.batch: INFO
